runtime: python37
entrypoint: gunicorn -b :$PORT wishlist.wsgi

handlers:
- url: /static
  static_dir: www/static

- url: /.*
  script: auto

env_variables:
  TRAVELER_PW: Capstone_!

beta_settings:
  cloud_sql_instances: travel-wishlist-24749:us-central1:wishlist-db